<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Carbon\Carbon;

class MessageTest extends TestCase
{
    use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Artisan::call('migrate:refresh');
        Artisan::call('db:seed');
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_comment(){

        $data = [
            'description' => 'First message',
            'time_sent' => Carbon::parse('2016-12-14 14:50:32')->format('Y-m-d H:i:s'),
            'owner_id' => 2,
            'event_id' => 25
        ];
        $this->json('POST', "api/messages", $data)->seeStatusCode(200)->decodeResponseJson();
    }

    public function test_delete(){
        $response = $this->call('DELETE', "api/deleteComment/44/24");
        print "$response";
        $this->assertEquals('200 User with id 44 deleted comment with id 24', $response->status() . ' ' . $response->getContent());
    }

    public function test_edit(){
        //TODO
    }
}


